
const HASH_ALGORITHM = 'SHA-256';

const SYMMETRIC_KEY_ALGORITHM = 'AES-GCM'
const SYMMETRIC_KEY_LENGTH = 256
const IV_LENGTH = 12

const ASYMMETRIC_KEY_ALGORITHM = 'RSA-OAEP'
const ASYMMETRIC_PUBLIC_EXPONENT = "AQAB"

const KEY_DERIVATION_FUNCTION = 'PBKDF2'
const KEY_DERIVATION_ITERATION_COUNT = 150000
const SALT_LENGTH = 16

const HD_SIGNING_PATH = 'm/0\'/0\'/0'
const HD_ENCRYPTION_PATH = 'm/1\'/0\'/0'

const VAULT_CREATE = 'vault:create'
const VAULT_UPDATE = 'vault:update'
const MEMBERSHIP_UPDATE = 'membership:update'
const MEMBERSHIP_OWNER = 'membership:owner'
const MEMBERSHIP_INVITE = 'membership:invite'
const MEMBERSHIP_ACCEPT = 'membership:accept'
const MEMBERSHIP_REJECT = 'membership:reject'
const MEMBERSHIP_REVOKE = 'membership:revoke'
const STACK_CREATE = 'stack:create'
const STACK_UPDATE = 'stack:update'
const MEMO_CREATE = 'memo:create'

module.exports = {
  HASH_ALGORITHM,
  SYMMETRIC_KEY_ALGORITHM,
  SYMMETRIC_KEY_LENGTH,
  IV_LENGTH,
  ASYMMETRIC_KEY_ALGORITHM,
  ASYMMETRIC_PUBLIC_EXPONENT,
  KEY_DERIVATION_FUNCTION,
  KEY_DERIVATION_ITERATION_COUNT,
  SALT_LENGTH,
  HD_SIGNING_PATH,
  HD_ENCRYPTION_PATH,
  VAULT_CREATE,
  VAULT_UPDATE,
  MEMBERSHIP_UPDATE,
  MEMBERSHIP_OWNER,
  MEMBERSHIP_INVITE,
  MEMBERSHIP_ACCEPT,
  MEMBERSHIP_REJECT,
  MEMBERSHIP_REVOKE,
  STACK_CREATE,
  STACK_UPDATE,
  MEMO_CREATE
}