
const HASH_ALGORITHM = 'SHA-256';

const SYMMETRIC_KEY_ALGORITHM = 'AES-GCM'
const SYMMETRIC_KEY_LENGTH = 256
const IV_LENGTH = 12

const ASYMMETRIC_KEY_ALGORITHM = 'RSA-OAEP'
const ASYMMETRIC_PUBLIC_EXPONENT = "AQAB"

const KEY_DERIVATION_FUNCTION = 'PBKDF2'
const KEY_DERIVATION_ITERATION_COUNT = 150000
const SALT_LENGTH = 16

const HD_SIGNING_PATH = 'm/0\'/0\'/0'
const HD_ENCRYPTION_PATH = 'm/1\'/0\'/0'

const SVP_VAULT_CREATE = 'svp:vault:create'
const SVP_VAULT_UPDATE = 'svp:vault:update'
const SVP_MEMBERSHIP_UPDATE = 'svp:membership:update'
const SVP_MEMBERSHIP_OWNER = 'svp:membership:owner'
const SVP_MEMBERSHIP_INVITE = 'svp:membership:invite'
const SVP_MEMBERSHIP_ACCEPT = 'svp:membership:accept'
const SVP_MEMBERSHIP_REJECT = 'svp:membership:reject'
const SVP_MEMBERSHIP_REVOKE = 'svp:membership:revoke'
const SVP_STACK_CREATE = 'svp:stack:create'
const SVP_STACK_UPDATE = 'svp:stack:update'
const SVP_MEMO_CREATE = 'svp:memo:create'

module.exports = {
  HASH_ALGORITHM,
  SYMMETRIC_KEY_ALGORITHM,
  SYMMETRIC_KEY_LENGTH,
  IV_LENGTH,
  ASYMMETRIC_KEY_ALGORITHM,
  ASYMMETRIC_PUBLIC_EXPONENT,
  KEY_DERIVATION_FUNCTION,
  KEY_DERIVATION_ITERATION_COUNT,
  SALT_LENGTH,
  HD_SIGNING_PATH,
  HD_ENCRYPTION_PATH,
  SVP_VAULT_CREATE,
  SVP_VAULT_UPDATE,
  SVP_MEMBERSHIP_UPDATE,
  SVP_MEMBERSHIP_OWNER,
  SVP_MEMBERSHIP_INVITE,
  SVP_MEMBERSHIP_ACCEPT,
  SVP_MEMBERSHIP_REJECT,
  SVP_MEMBERSHIP_REVOKE,
  SVP_STACK_CREATE,
  SVP_STACK_UPDATE,
  SVP_MEMO_CREATE
}